[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}

[project]
name = "generator"
version = "0.0.1"
authors = "rafpro33@geoteko.com.pl"
description = "Sample project for medium article"
readme = "README.md"